name: website 
on:
  push:
    branches: ['*']
    
jobs:
    job1:
        name : Install packages
        runs-on: ubuntu-latest
        steps:
            - name : install npm 
              uses : actions/checkout@v2
            - run : sudo apt install npm nodejs
              shell: bash
            
    job2:
        name : upgrade packages
        runs-on: ubuntu-latest
        steps:
            - name :  upgrade packages to latest
              uses : actions/checkout@v2
            - run : npm install -g npm       
              shell: bash
           